### ISSUE TITLE
换了新上的cdn上去，加载不出来页面，麻烦作者紧急修复一下

### ISSUE THREAD

**Issue by lzmoj0906** [TheSmallHanCat/Better_Alist#2]

**Comment by TheSmallHanCat** [comment]
可以麻烦看一下F12控制台报错嘛，如果显示超时，说明你那个地区cdn.jsdelivr.net被墙了

我这里显示没有问题
目前就那个随机背景图的api出了点问题，但是新cdn的css和js可以正常调用

**Comment by lzmoj0906** [comment]
现在已经好了

**Comment by lzmoj0906** [comment]
![image](https://github.com/TheSmallHanCat/Better_Alist/assets/149756889/7a672ae2-bb5a-4fd6-bed2-6b88dcfc322d)
真的被去q了，可以换一个国内能访问的吗

**Comment by lzmoj0906** [comment]
> 可以麻烦看一下F12控制台报错嘛，如果显示超时，说明你那个地区cdn.jsdelivr.net被墙了
> 
> 我这里显示没有问题 目前就那个随机背景图的api出了点问题，但是新cdn的css和js可以正常调用

大佬有时间弄一下吗？

**Comment by TheSmallHanCat** [comment]
修好啦
