### ISSUE TITLE
国内访问不到cdn呀，可以修复一下吗

### ISSUE THREAD

**Issue by lzmoj0906** [TheSmallHanCat/Better_Alist#3]

**Comment by TheSmallHanCat** [comment]
抱歉这两天在学校比较忙
现已经将cdn换为国内可以访问的加速链接

**Comment by TheSmallHanCat** [comment]
你可以将css和js文件下载下来放到自己的服务器内，然后在alist中直接去加载，或者使用github镜像站来加载仓库内的文件
经测试全国有部分地区被墙了，我也没有办法
![image](https://github.com/TheSmallHanCat/Better_Alist/assets/109069769/3f500354-52fd-476b-8955-0712232af660)
