### ISSUE TITLE
在线看视频也变透明了qwq

### ISSUE THREAD

**Issue by zerof19** [TheSmallHanCat/Better_Alist#4]
大佬还有在维护吗，很喜欢您这个美化包，不知道该怎么修改

**Comment by TheSmallHanCat** [comment]
网页全屏会透明，但是浏览器全屏木有影响
可能是css属性没有区分开叭，后面再研究研究


想自己修改样式的话，可以fork仓库，然后修改'''alist.css'''里面的样式，最后把readme里面的链接换成自己仓库就阔以了

**Comment by TheSmallHanCat** [comment]
网页全屏会透明，但是浏览器全屏木有影响
可能是css属性没有区分开叭，后面再研究研究

想自己修改样式的话，可以fork仓库，然后修改```alist.css```里面的样式，最后把readme里面的链接换成自己仓库就阔以了

**Comment by TheSmallHanCat** [comment]
修好啦
